#184752273 User should be prompted to change their passwords
atlp-rwanda/e-comm-team-techtitans-bn pull request #55
Opened 2023-04-13 12:13 UTC by Rod-code

#### What does this PR do?
User should be prompted to change their passwords every x amount of time 
since the time it was either manually updated.

2023-04-13 13:38 UTC, David-Neza approved these changes

2023-04-13 13:39 UTC, rich26638 approved these changes

2023-04-13 13:48 UTC, Folio123-c reviewed
Uncomment those code [config.js] for staging and production environment, Also  There is localhost link in  your code

2023-04-13 13:51 UTC, Folio123-c requested changes
Uncomment those code [config.js] for staging and production environment, Also There is localhost link in your code[password.reminder.js]

2023-04-13 14:12 UTC, Folio123-c approved these changes

2023-04-14 06:54 UTC, shemajolivetgislain approved these changes

2023-04-14 06:58 UTC, merged