#184752269 ft(buyer-make-payments):Buyer should be able to make a payment using Stripe API
atlp-rwanda/e-comm-team-techtitans-bn pull request #57
Opened 2023-04-13 15:55 UTC by rich26638

### what does this PR do?
-allows users to make payments from their bank account
### how to test this manually
-clone this repo
-switch to this branch "ft-buyer-make-payment"
-run "npm install"
-run "npm run dev"

2023-04-17 09:40 UTC, Cynthia-kam approved these changes

2023-04-17 09:40 UTC, shemajolivetgislain approved these changes

2023-04-17 09:41 UTC, Rod-code approved these changes

2023-04-17 09:41 UTC, Folio123-c approved these changes

2023-04-17 10:16 UTC, EdwinBayingana approved these changes

2023-04-17 13:23 UTC, NdatimanaSamuel approved these changes

2023-04-17 13:31 UTC, Gentille-dev approved these changes
check

2023-04-17 16:32 UTC, nshutijonathan requested changes
Can you please add relevant screenshot to your PRs

add also PT board link

2023-04-18 10:13 UTC, nshutijonathan approved these changes
LGTM

2023-04-18 10:24 UTC, merged