#[184752266]:A user should be able to search a product
atlp-rwanda/e-comm-team-techtitans-bn pull request #60
Opened 2023-04-14 11:28 UTC by Vg1k

what this pr do 
enable use to search product based on category, price , and product name

2023-04-16 14:13 UTC, Folio123-c approved these changes

2023-04-18 11:26 UTC, madebypatrick approved these changes

2023-04-18 11:28 UTC, Rod-code approved these changes

2023-04-18 11:40 UTC, EdwinBayingana requested changes
The tests are not passing, they need a fix.

2023-04-18 12:49 UTC, EdwinBayingana approved these changes

2023-04-19 08:51 UTC, merged