#184829215 sellers will mark orders as "shipped"
atlp-rwanda/e-comm-team-techtitans-bn pull request #61
Opened 2023-04-15 09:39 UTC by Cynthia-kam

#### What does this PR do?
It allows sellers to update the order's status to "shipped" after delivering the product
#### How should this be manually tested?
1. Run seeders to create an order seed in database : npm run seed:dev:do
2. Log in as a "seller"
3. Hit route "/product/order/updatestatus/:id" where "id" is the id of a seed created
#### What are the relevant pivotal tracker/Trello stories?
storyID: #184829215
story Title: Sellers should be able to update the orders

2023-04-17 10:29 UTC, rich26638 approved these changes

2023-04-17 10:36 UTC, Folio123-c approved these changes

2023-04-17 12:29 UTC, Rod-code approved these changes

2023-04-17 16:34 UTC, nshutijonathan requested changes
can make this a hyperlink `storyID: #184829215`?

You can also add relevant screenshots

2023-04-18 10:22 UTC, nshutijonathan approved these changes
LGTM

2023-04-20 18:02 UTC, merged